# Generated by Django 5.2.7 on 2025-11-13 12:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("welcome_section", 5), ("highlight", 8)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Welcome to St. Mark University",
                            "help_text": "Text for the welcome badge",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Shaping Leaders, Advancing Knowledge",
                            "help_text": "Main heading text",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "At St. Mark University, we are committed to providing world-class education that prepares students for success in an ever-changing global landscape. Our diverse community of scholars, researchers, and innovators work together to push the boundaries of knowledge and create positive impact in society.",
                            "help_text": "Description paragraph text",
                            "max_length": 1000,
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Highlight points", "max_length": 200},
                    ),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (3,),
                        {
                            "default": [
                                "Over 40 years of academic excellence",
                                "Distinguished faculty with industry expertise",
                                "State-of-the-art research facilities",
                                "Global partnerships and exchange programs",
                                "95% graduate employment rate",
                            ],
                            "help_text": "List of highlight points",
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("welcome_text", 0),
                                ("heading", 1),
                                ("description", 2),
                                ("highlights", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("description", 7)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
