# Generated by Django 5.2.8 on 2025-11-14 09:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("welcome_section", 5),
                    ("news_section", 14),
                    ("events_section", 24),
                    ("gallery_section", 31),
                    ("testimonials_section", 39),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Welcome to St. Mark University",
                            "help_text": "Text for the welcome badge",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Shaping Leaders, Advancing Knowledge",
                            "help_text": "Main heading text",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "At St. Mark University, we are committed to providing world-class education that prepares students for success in an ever-changing global landscape. Our diverse community of scholars, researchers, and innovators work together to push the boundaries of knowledge and create positive impact in society.",
                            "help_text": "Description paragraph text",
                            "max_length": 1000,
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Highlight points", "max_length": 200},
                    ),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (3,),
                        {
                            "default": [
                                "Over 40 years of academic excellence",
                                "Distinguished faculty with industry expertise",
                                "State-of-the-art research facilities",
                                "Global partnerships and exchange programs",
                                "95% graduate employment rate",
                            ],
                            "help_text": "List of highlight points",
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("welcome_text", 0),
                                ("heading", 1),
                                ("description", 2),
                                ("highlights", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Latest News & Announcements",
                            "help_text": "Section heading",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    7: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Stay updated with the latest happenings, achievements, and events at St. Mark University.",
                            "help_text": "Section subheading or description",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "News title",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Publication date",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Brief excerpt of the news article",
                            "max_length": 500,
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "News image", "required": True},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 8), ("date", 9), ("excerpt", 10), ("image", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {"help_text": "List of news items"},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 6), ("subheading", 7), ("news_items", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Upcoming Events",
                            "help_text": "Section heading",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    16: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Join us for exciting events, workshops, and activities throughout the academic year.",
                            "help_text": "Section description",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Event title",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Event date",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Event time",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Event location",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    21: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Event description",
                            "max_length": 500,
                            "required": True,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 17),
                                ("date", 18),
                                ("time", 19),
                                ("location", 20),
                                ("description", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {"help_text": "List of events"},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 15), ("description", 16), ("events", 23)]],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Campus Life",
                            "help_text": "Section heading",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    26: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Experience the vibrant community and beautiful campus at St. Mark University.",
                            "help_text": "Section description",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Gallery image", "required": True},
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Alternative text for the image",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 27), ("alt_text", 28)]],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.ListBlock",
                        (29,),
                        {
                            "help_text": "List of gallery images",
                            "max_num": 4,
                            "min_num": 4,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 25),
                                ("description", 26),
                                ("gallery_images", 30),
                            ]
                        ],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "What Our Community Says",
                            "help_text": "Section heading",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    33: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Hear from students, faculty, and alumni about their experiences at St. Mark University.",
                            "help_text": "Section description",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Name of the person giving the testimonial",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Role/position of the person (e.g., 'Computer Science Graduate, Class of 2024')",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    36: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "The testimonial text",
                            "max_length": 1000,
                            "required": True,
                        },
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 34), ("role", 35), ("quote", 36)]],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.ListBlock",
                        (37,),
                        {
                            "help_text": "List of testimonials",
                            "max_num": 3,
                            "min_num": 3,
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 32), ("description", 33), ("testimonials", 38)]],
                        {},
                    ),
                },
            ),
        ),
    ]
